java_binary(
    name = "bazel",
    main_class = "starlord.Main",
    srcs = [
        "Main.java",
    ],
    runtime_deps = [
        "//src/main/java/net/starlark/java/syntax",
        "//src/main/java/net/starlark/java/eval",
        "//src/main/java/net/starlark/java/annot",
        "//src/main/java/net/starlark/java/annot/processor",
    ],
)
